-LC:\borland\bcc55\lib\obj;C:\borland\bcc55\lib;C:\develop\xharbour\1.20\lib -Gn -M -m -s -Tpe -x -aa +
c0w32.obj \BPOS.obj \ACME.obj \APCHEQUE.obj \APEOM.obj \APREMIT.obj \APREP.obj \APTRAN.obj \AREOM.obj \ARREP.obj \ARSTAT.obj \ARTRAN.obj \DPURORD.obj \ERRORSYS.obj \FPURORD.obj \INVFORMS.obj \MAINCATE.obj \MAINCUST.obj \MAINDEPT.obj \MAINITEM.obj \MAINSUPP.obj \PRINTFUNC.obj \PROCLIB.obj \PURCKIT.obj \RECEIVE.obj \RECLIST.obj \RECPOST.obj \RETURNS.obj \SETUPDBF.obj \S_APPR.obj \S_ARCH.obj \S_CASH.obj \S_DAILY.obj \S_INQ1.obj \S_INQ2.obj \S_INV1.obj \S_INV2.obj \S_LAYB.obj \S_QUOTE.obj \S_REPO.obj \S_SPEC.obj \UTILARCH.obj \UTILBACK.obj \UTILCOND.obj \UTILLABE.obj \UTILPACK.obj \UTILREPR.obj \UTILSPPA.obj \UTILSTOC.obj, +
bpos.exe,, +
gtwvw.lib lang.lib vm.lib rtl.lib rdd.lib macro.lib pp.lib dbfntx.lib dbfcdx.lib dbffpt.lib common.lib codepage.lib ct.lib tip.lib pcrepos.lib hsx.lib hbsix.lib zlib.lib telepath.lib import32.lib cw32.lib, +
, +
BPOS.RES
