-LC:\borland\bcc55\lib\obj;C:\borland\bcc55\lib;C:\develop\xharbour\1.2.3\lib -Gn -M -m -s -Tpe -x -aa +
c0w32.obj obj\BPOS.obj obj\ACME.obj obj\APCHEQUE.obj obj\APEOM.obj obj\APREMIT.obj obj\APREP.obj obj\APTRAN.obj obj\AREOM.obj obj\ARREP.obj obj\ARSTAT.obj obj\ARTRAN.obj obj\DPURORD.obj obj\ERRORSYS.obj obj\FPURORD.obj obj\INVFORMS.obj obj\MAINCATE.obj obj\MAINCUST.obj obj\MAINDEPT.obj obj\MAINITEM.obj obj\MAINSUPP.obj obj\PRINTFUNC.obj obj\PROCLIB.obj obj\PURCKIT.obj obj\RECEIVE.obj obj\RECLIST.obj obj\RECPOST.obj obj\RETURNS.obj obj\SETUPDBF.obj obj\S_APPR.obj obj\S_ARCH.obj obj\S_CASH.obj obj\S_DAILY.obj obj\S_INQ1.obj obj\S_INQ2.obj obj\S_INV1.obj obj\S_INV2.obj obj\S_LAYB.obj obj\S_QUOTE.obj obj\S_REPO.obj obj\S_SPEC.obj obj\UTILARCH.obj obj\UTILBACK.obj obj\UTILCOND.obj obj\UTILLABE.obj obj\UTILPACK.obj obj\UTILREPR.obj obj\UTILSPPA.obj obj\UTILSTOC.obj, +
bpos.exe,, +
lang.lib vm.lib rtl.lib rdd.lib macro.lib pp.lib dbfntx.lib dbfcdx.lib dbffpt.lib common.lib gtwvw.lib codepage.lib ct.lib tip.lib pcrepos.lib hsx.lib hbsix.lib zlib.lib import32.lib cw32.lib, +
, +
BPOS.RES
